# coding: utf-8

# flake8: noqa
"""
    CVPartner

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from scienta.cvpartner_api.models.certification import Certification
from scienta.cvpartner_api.models.country import Country
from scienta.cvpartner_api.models.course import Course
from scienta.cvpartner_api.models.cv import Cv
from scienta.cvpartner_api.models.cv_list import CvList
from scienta.cvpartner_api.models.cv_list_entry import CvListEntry
from scienta.cvpartner_api.models.cv_section import CvSection
from scienta.cvpartner_api.models.cv_section_properties import CvSectionProperties
from scienta.cvpartner_api.models.cv_summary import CvSummary
from scienta.cvpartner_api.models.education import Education
from scienta.cvpartner_api.models.image_url import ImageUrl
from scienta.cvpartner_api.models.key_qualification import KeyQualification
from scienta.cvpartner_api.models.language import Language
from scienta.cvpartner_api.models.office import Office
from scienta.cvpartner_api.models.position import Position
from scienta.cvpartner_api.models.presentation import Presentation
from scienta.cvpartner_api.models.project_experience import ProjectExperience
from scienta.cvpartner_api.models.project_role import ProjectRole
from scienta.cvpartner_api.models.recommendation import Recommendation
from scienta.cvpartner_api.models.search_by_name_req import SearchByNameReq
from scienta.cvpartner_api.models.technology import Technology
from scienta.cvpartner_api.models.user import User
from scienta.cvpartner_api.models.user_image import UserImage
from scienta.cvpartner_api.models.work_experience import WorkExperience
