[browser]
gatherUsageStats = false

[server]
headless = true
folderWatchBlacklist = ["log"]

[logger]
level = "info"
messageFormat = "%(levelname)-7s %(name)-40s - %(message)s"

#messageFormat = "%(asctime)s %(levelname)-7s %(name)-40s - %(message)s"
